// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig } from "prisma/config";
const DATABASE_URL="mysql://root:ADITYA21@localhost:3307/airbnb_booking_dev"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
// import dotenv from "dotenv";
// import path from "path";

// dotenv.config({
//   path: path.resolve(process.cwd(), ".env"),
// });

// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// });
